export const LOAD_NEWS_REQUEST = 'LOAD_NEWS_REQUEST'
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS'
export const LOAD_NEWS_FAILURE = 'LOAD_NEWS_FAILURE'

export const LOAD_NEWSLIST_REQUEST = 'LOAD_NEWSLIST_REQUEST'
export const LOAD_NEWSLIST_SUCCESS = 'LOAD_NEWSLIST_SUCCESS'
export const LOAD_NEWSLIST_FAILURE = 'LOAD_NEWSLIST_FAILURE'
